import { useInView } from '../hooks/useInView'
import { cn } from '../lib/utils'

export default function AISummary() {
  const { ref, inView } = useInView()

  return (
    <section className="py-40 px-6 bg-[#f5f5f7]">
      <div className="max-w-3xl mx-auto text-center">
        <div
          ref={ref as React.RefObject<HTMLDivElement>}
          className={cn('fade-up', inView && 'in-view')}
        >
          <p className="text-[11px] font-semibold tracking-[0.22em] uppercase text-[#0071e3] mb-12 select-none">
            AI Summary
          </p>

          {/* The quote — this IS the section */}
          <blockquote
            className="text-[26px] md:text-[30px] font-medium tracking-[-0.02em] leading-[1.38] text-[#1d1d1f]"
            style={{ fontStyle: 'normal' }}
          >
            <span className="text-[#0071e3] mr-1" style={{ fontSize: '1.2em', lineHeight: 0, verticalAlign: '-0.1em' }}>"</span>
            Your app is nearly ready for App Store submission. The remaining
            blockers are a missing Privacy Policy URL and incomplete StoreKit
            metadata.
            <span className="text-[#0071e3] ml-1" style={{ fontSize: '1.2em', lineHeight: 0, verticalAlign: '-0.1em' }}>"</span>
          </blockquote>

          <div className="mt-10 flex items-center justify-center gap-2">
            <div className="w-1.5 h-1.5 rounded-full bg-[#0071e3]" />
            <p className="text-[13px] text-[#6e6e73]">
              Generated by PreFlight AI · Updated with every scan
            </p>
          </div>
        </div>
      </div>
    </section>
  )
}
